services:
  llm-server:
    # build: 
    #   context: ./LLM-Server
    #   dockerfile: Dockerfile
    image: kingrange/dcba-llm-server:latest
    container_name: llm-server
    ports:
      - "${LLM_SERVER_PORT}:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    depends_on:
      - redis
      - mariadb
    networks:
      - dcba-network
    restart: always

  dcba-app:
    # build:
    #   context: ./DCBA
    #   dockerfile: Dockerfile
    image: kingrange/dcba-java-app:latest
    container_name: dcba-app
    ports:
      - "${DCBA_SERVER_PORT}:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    depends_on:
      - mariadb
    networks:
      - dcba-network
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "${EXTERNAL_REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - dcba-network
    restart: always

  mariadb:
    image: mariadb:10.11
    container_name: mariadb-server
    ports:
      - "${EXTERNAL_MARIADB_PORT}:3306"
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - dcba-network
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - dcba-network
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - dcba-network
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - dcba-network
    restart: always

volumes:
  redis_data:
  mariadb_data:
  prometheus_data:
  grafana_data:

networks:
  dcba-network:
    driver: bridge
