services:
  llm-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: llm-server

    ports:
      - "${LLM_SERVER_PORT}:8000"

    env_file:
      - .env

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306

    depends_on:
      - redis
      - mariadb
      
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_tokens:/data
    restart: always

  mariadb:
    image: mariadb:10.11
    container_name: mariadb-server
    ports:
      - "${MARIADB_PORT}:3306"
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  redis_tokens:
  mariadb_data:
